### ISSUE TITLE
Nil pointer issues accessing utf8 library in v3.5

### ISSUE THREAD

**Issue by chrishenzie** [Snocean/ProEnchanters#1]
In v3.5 (on CurseForge) I'm getting nil pointer errors like the following when trying to call `string.utf8lower2`:
```
Message: Interface/AddOns/ProEnchanters/ProEnchanters.lua:5051: attempt to call field 'utf8lower2' (a nil value)
Time: Fri Feb 23 22:50:06 2024
Count: 1
Stack: Interface/AddOns/ProEnchanters/ProEnchanters.lua:5051: attempt to call field 'utf8lower2' (a nil value)
[string "@Interface/AddOns/ProEnchanters/ProEnchanters.lua"]:5051: in function `ProEnchantersTradeWindowCreateFrame'
[string "@Interface/AddOns/ProEnchanters/ProEnchanters.lua"]:6177: in function <Interface/AddOns/ProEnchanters/ProEnchanters.lua:5934>
[string "@Interface/AddOns/ProEnchanters/ProEnchanters.lua"]:6195: in function <Interface/AddOns/ProEnchanters/ProEnchanters.lua:6192>
```

It looks like the offending line was removed in https://github.com/Snocean/ProEnchanters/commit/b201b77c0d2492d78e57c79bc67f03a7c1905361, however I think this might still be an issue elsewhere.

I don't have LUA experience, but I suspect the utf8 library isn't being loaded, so then [`string.utf8lower2` is never added](https://github.com/Snocean/ProEnchanters/blob/b201b77c0d2492d78e57c79bc67f03a7c1905361/libs/utf8.lua#L280-L283), which causes this issue. I'll need to investigate this more to figure out how imports actually work / if this is the root cause.

**Comment by Snocean** [comment]
I found the issue may be due to me using a / instead of a \ for the lib file within the .toc, when loading wow with only pro enchanters addon and the changed slash it now seems to be working as expected, will be pushing this addon update shortly to curseforge and updating github afterwards

**Comment by Snocean** [comment]
Some other players have confirmed that it's working now as well, will update github with the new files
